version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      go-deps:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /ml_service
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: torch
      - dependency-name: torchaudio

  - package-ecosystem: npm
    directory: /ui
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      ui-deps:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: docker
    directory: /docker
    schedule:
      interval: monthly
