package observability

import (
	"net/http"
	"strconv"
	"time"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

var (
	httpRequestsTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "holodub_http_requests_total",
		Help: "Total HTTP requests served by the API.",
	}, []string{"method", "path", "status"})

	httpRequestDuration = promauto.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "holodub_http_request_duration_seconds",
		Help:    "HTTP request duration in seconds.",
		Buckets: prometheus.DefBuckets,
	}, []string{"method", "path"})

	stageRunsTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "holodub_stage_runs_total",
		Help: "Total pipeline stage runs by stage and status.",
	}, []string{"stage", "status"})

	stageRunDuration = promauto.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "holodub_stage_run_duration_seconds",
		Help:    "Pipeline stage run duration in seconds.",
		Buckets: prometheus.DefBuckets,
	}, []string{"stage"})

	deadLettersTotal = promauto.NewCounter(prometheus.CounterOpts{
		Name: "holodub_dead_letters_total",
		Help: "Number of tasks moved into the dead letter queue.",
	})

	externalCallsTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "holodub_external_calls_total",
		Help: "Outbound calls to external services (llm, ml) by classification.",
	}, []string{"service", "operation", "result"})

	externalCallDuration = promauto.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "holodub_external_call_duration_seconds",
		Help:    "Outbound external call latency in seconds.",
		Buckets: prometheus.DefBuckets,
	}, []string{"service", "operation"})

	// LLM token usage. Keep cardinality low: model + operation only.
	// operation values: translate | retranslate | retranslate_thinking | summary | review | judge.
	// OPT-001: cached_tokens lets us see prompt-prefix cache hit rate per provider.
	llmInputTokensTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "holodub_llm_input_tokens_total",
		Help: "Total prompt (input) tokens consumed by LLM calls.",
	}, []string{"model", "operation"})

	llmOutputTokensTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "holodub_llm_output_tokens_total",
		Help: "Total completion (output) tokens generated by LLM calls.",
	}, []string{"model", "operation"})

	llmCachedTokensTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "holodub_llm_cached_tokens_total",
		Help: "Total prompt tokens served from provider-side prefix cache (subset of input tokens).",
	}, []string{"model", "operation"})

	// OPT-003: count strict-JSON / function-calling parse failures so we can
	// monitor the tool-call path's reliability and decide when to retire the
	// legacy prompt+JSON.Unmarshal fallback.
	llmStrictParseFailedTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "holodub_llm_strict_parse_failed_total",
		Help: "Times the strict JSON / tool-call parse failed and the caller fell back to legacy parsing.",
	}, []string{"operation"})
)

// ObserveExternalCall records the outcome of an outbound HTTP call to a
// dependency (LLM provider, ml-service, …). result is one of:
//   - "ok"           — call succeeded
//   - "retryable"    — failed but classified as retryable (429/5xx/network)
//   - "permanent"    — failed and not retryable (4xx other than 429)
//   - "cancelled"    — context cancelled / deadline exceeded
func ObserveExternalCall(service, operation, result string, duration time.Duration) {
	externalCallsTotal.WithLabelValues(service, operation, result).Inc()
	externalCallDuration.WithLabelValues(service, operation).Observe(duration.Seconds())
}

func ObserveHTTPRequest(method, path string, statusCode int, duration time.Duration) {
	status := strconv.Itoa(statusCode)
	httpRequestsTotal.WithLabelValues(method, path, status).Inc()
	httpRequestDuration.WithLabelValues(method, path).Observe(duration.Seconds())
}

func ObserveStageRun(stage, status string, duration time.Duration) {
	stageRunsTotal.WithLabelValues(stage, status).Inc()
	stageRunDuration.WithLabelValues(stage).Observe(duration.Seconds())
}

func IncDeadLetters() {
	deadLettersTotal.Inc()
}

// ObserveLLMTokens records token usage for one LLM call.
// promptTokens is the TOTAL input tokens (cached + non-cached).
// cachedTokens is the subset served from provider prefix cache (0 if no cache or unsupported).
// model is the actual model name (e.g. "qwen-turbo", "kimi-k2.5"); operation is one of
// translate | retranslate | retranslate_thinking | summary | review | judge.
//
// Observe failures are swallowed — observability MUST NOT block the main flow
// (see .cursor/rules/observability-and-cost.mdc#6).
func ObserveLLMTokens(model, operation string, promptTokens, completionTokens, cachedTokens int) {
	if model == "" {
		model = "unknown"
	}
	if operation == "" {
		operation = "unknown"
	}
	if promptTokens > 0 {
		llmInputTokensTotal.WithLabelValues(model, operation).Add(float64(promptTokens))
	}
	if completionTokens > 0 {
		llmOutputTokensTotal.WithLabelValues(model, operation).Add(float64(completionTokens))
	}
	if cachedTokens > 0 {
		llmCachedTokensTotal.WithLabelValues(model, operation).Add(float64(cachedTokens))
	}
}

// IncLLMStrictParseFailed increments the OPT-003 fallback counter. operation
// is the same set used in ObserveLLMTokens (typically "review" today, more
// once OPT-002/204 land).
func IncLLMStrictParseFailed(operation string) {
	if operation == "" {
		operation = "unknown"
	}
	llmStrictParseFailedTotal.WithLabelValues(operation).Inc()
}

func MetricsHandler() http.Handler {
	return promhttp.Handler()
}
