package observability

import (
	"net/http"
	"strconv"
	"time"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

var (
	httpRequestsTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "holodub_http_requests_total",
		Help: "Total HTTP requests served by the API.",
	}, []string{"method", "path", "status"})

	httpRequestDuration = promauto.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "holodub_http_request_duration_seconds",
		Help:    "HTTP request duration in seconds.",
		Buckets: prometheus.DefBuckets,
	}, []string{"method", "path"})

	stageRunsTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "holodub_stage_runs_total",
		Help: "Total pipeline stage runs by stage and status.",
	}, []string{"stage", "status"})

	stageRunDuration = promauto.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "holodub_stage_run_duration_seconds",
		Help:    "Pipeline stage run duration in seconds.",
		Buckets: prometheus.DefBuckets,
	}, []string{"stage"})

	deadLettersTotal = promauto.NewCounter(prometheus.CounterOpts{
		Name: "holodub_dead_letters_total",
		Help: "Number of tasks moved into the dead letter queue.",
	})

	externalCallsTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "holodub_external_calls_total",
		Help: "Outbound calls to external services (llm, ml) by classification.",
	}, []string{"service", "operation", "result"})

	externalCallDuration = promauto.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "holodub_external_call_duration_seconds",
		Help:    "Outbound external call latency in seconds.",
		Buckets: prometheus.DefBuckets,
	}, []string{"service", "operation"})

	// LLM token usage. Keep cardinality low: model + operation only.
	// operation values: translate | retranslate | retranslate_thinking | summary | review | judge.
	// OPT-001: cached_tokens lets us see prompt-prefix cache hit rate per provider.
	llmInputTokensTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "holodub_llm_input_tokens_total",
		Help: "Total prompt (input) tokens consumed by LLM calls.",
	}, []string{"model", "operation"})

	llmOutputTokensTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "holodub_llm_output_tokens_total",
		Help: "Total completion (output) tokens generated by LLM calls.",
	}, []string{"model", "operation"})

	llmCachedTokensTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "holodub_llm_cached_tokens_total",
		Help: "Total prompt tokens served from provider-side prefix cache (subset of input tokens).",
	}, []string{"model", "operation"})

	// OPT-003: count strict-JSON / function-calling parse failures so we can
	// monitor the tool-call path's reliability and decide when to retire the
	// legacy prompt+JSON.Unmarshal fallback.
	llmStrictParseFailedTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "holodub_llm_strict_parse_failed_total",
		Help: "Times the strict JSON / tool-call parse failed and the caller fell back to legacy parsing.",
	}, []string{"operation"})

	// OPT-407: dollar cost per LLM call, derived from token counts via the
	// hardcoded model price table in internal/llm/pricing.go. Lets us
	// dashboard the production cost of every LLM use case independently
	// and compare against the per-episode rework cost ceiling. Cardinality
	// stays at model × operation (same as the token counters above).
	llmCostUSDTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "holodub_llm_cost_usd_total",
		Help: "Estimated USD cost of LLM calls, derived from token usage and the per-model price table.",
	}, []string{"model", "operation"})

	// OPT-407: count of rework engine decisions broken down by level
	// (segment / chapter / episode), action type, and whether the action
	// was actually dispatched (vs persisted-only). Lets a dashboard
	// alert on "rework engine refusing to dispatch because of cost
	// ceiling" or "thousands of segment retries" without inspecting the
	// rework_attempts JSONB column row-by-row.
	reworkActionsTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "holodub_rework_actions_total",
		Help: "Count of OPT-407 rework engine decisions by level, action type, and whether dispatched.",
	}, []string{"level", "action", "dispatched"})

	// OPT-201: count of SegmentAgent decisions broken down by decision
	// kind (accept / retranslate), reason (within_threshold / borrow_from_gap /
	// over_short_gap / under_run_drift / no_more_attempts / clip_overflow /
	// retranslation_disabled / retranslate_failed), and whether the
	// reasoning model was selected.
	//
	// Label cardinality is bounded: 2 kinds × ~8 reasons × 2 thinking
	// values = 32 series. The "use_thinking" label distinguishes when
	// the agent escalated to the slower reasoning model so dashboards
	// can alert on "thinking-mode escalation rate" without joining
	// against the decision string itself.
	//
	// Label naming follows the OTEL gen_ai convention as closely as
	// possible (lowercase snake_case, low cardinality) so OPT-101's
	// OpenTelemetry exporter can re-label these to gen_ai.* without
	// duplicating the series — see observability-and-cost.mdc §1.
	segmentAgentDecisionsTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "holodub_segment_agent_decisions_total",
		Help: "Count of OPT-201 SegmentAgent decisions by kind, reason, thinking-mode escalation, and ensemble escalation.",
	}, []string{"decision", "reason", "use_thinking", "use_ensemble"})

	// OPT-204-followup-1: count of strict-tool JSON parse failures that
	// were successfully recovered by tryRecoverDubbingPlanJSON. Lets a
	// dashboard answer "how often does the LLM emit ASCII " inside the
	// translation field?" without grep-ing logs. When this counter
	// stops growing AND the prompt fix is in place, the recovery
	// helper can be removed.
	llmRecoveredParseTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "holodub_llm_recovered_parse_total",
		Help: "Times a strict tool JSON parse failed but was recovered by a defensive helper.",
	}, []string{"operation"})
)

// ObserveExternalCall records the outcome of an outbound HTTP call to a
// dependency (LLM provider, ml-service, …). result is one of:
//   - "ok"           — call succeeded
//   - "retryable"    — failed but classified as retryable (429/5xx/network)
//   - "permanent"    — failed and not retryable (4xx other than 429)
//   - "cancelled"    — context cancelled / deadline exceeded
func ObserveExternalCall(service, operation, result string, duration time.Duration) {
	externalCallsTotal.WithLabelValues(service, operation, result).Inc()
	externalCallDuration.WithLabelValues(service, operation).Observe(duration.Seconds())
}

func ObserveHTTPRequest(method, path string, statusCode int, duration time.Duration) {
	status := strconv.Itoa(statusCode)
	httpRequestsTotal.WithLabelValues(method, path, status).Inc()
	httpRequestDuration.WithLabelValues(method, path).Observe(duration.Seconds())
}

func ObserveStageRun(stage, status string, duration time.Duration) {
	stageRunsTotal.WithLabelValues(stage, status).Inc()
	stageRunDuration.WithLabelValues(stage).Observe(duration.Seconds())
}

func IncDeadLetters() {
	deadLettersTotal.Inc()
}

// ObserveLLMTokens records token usage for one LLM call.
// promptTokens is the TOTAL input tokens (cached + non-cached).
// cachedTokens is the subset served from provider prefix cache (0 if no cache or unsupported).
// model is the actual model name (e.g. "qwen-turbo", "kimi-k2.5"); operation is one of
// translate | retranslate | retranslate_thinking | summary | review | judge.
//
// Observe failures are swallowed — observability MUST NOT block the main flow
// (see .cursor/rules/observability-and-cost.mdc#6).
func ObserveLLMTokens(model, operation string, promptTokens, completionTokens, cachedTokens int) {
	if model == "" {
		model = "unknown"
	}
	if operation == "" {
		operation = "unknown"
	}
	if promptTokens > 0 {
		llmInputTokensTotal.WithLabelValues(model, operation).Add(float64(promptTokens))
	}
	if completionTokens > 0 {
		llmOutputTokensTotal.WithLabelValues(model, operation).Add(float64(completionTokens))
	}
	if cachedTokens > 0 {
		llmCachedTokensTotal.WithLabelValues(model, operation).Add(float64(cachedTokens))
	}
}

// IncLLMStrictParseFailed increments the OPT-003 fallback counter. operation
// is the same set used in ObserveLLMTokens (typically "review" today, more
// once OPT-002/204 land).
func IncLLMStrictParseFailed(operation string) {
	if operation == "" {
		operation = "unknown"
	}
	llmStrictParseFailedTotal.WithLabelValues(operation).Inc()
}

// IncLLMRecoveredParse records one successful recovery from a strict tool
// JSON parse failure (OPT-204-followup-1). When the prompt fix lands and
// the recovery counter stops growing, the recovery helper can be removed.
func IncLLMRecoveredParse(operation string) {
	if operation == "" {
		operation = "unknown"
	}
	llmRecoveredParseTotal.WithLabelValues(operation).Inc()
}

// AddLLMCostUSD records the estimated dollar cost of one LLM call. usdCost
// is computed by internal/llm/pricing.ComputeUSD using the per-model price
// table — kept out of this file to avoid the import cycle the price table
// would otherwise trigger (pricing depends on observability for the
// counter, observability would otherwise depend on pricing for the math).
//
// Failures are swallowed (non-positive cost is dropped) — observability
// MUST NOT block the main flow.
func AddLLMCostUSD(model, operation string, usdCost float64) {
	if usdCost <= 0 {
		return
	}
	if model == "" {
		model = "unknown"
	}
	if operation == "" {
		operation = "unknown"
	}
	llmCostUSDTotal.WithLabelValues(model, operation).Add(usdCost)
}

// IncReworkAction records one OPT-407 rework engine decision. dispatched
// is "true" when the engine actually called RetryJob / EnqueueEpisodeStage,
// "false" when it persisted the attempt as observe-only (level disabled,
// halt, escalation, or noop).
//
// Cardinality stays low: 3 levels × ~10 action types × 2 dispatch states.
func IncReworkAction(level, action, dispatched string) {
	if level == "" {
		level = "unknown"
	}
	if action == "" {
		action = "unknown"
	}
	if dispatched == "" {
		dispatched = "false"
	}
	reworkActionsTotal.WithLabelValues(level, action, dispatched).Inc()
}

// IncSegmentAgentDecision records one OPT-201 SegmentAgent decision.
// kind is "accept" or "retranslate"; reason is the low-cardinality
// reason string from Decision.Reason (within_threshold, borrow_from_gap,
// over_short_gap, under_run_drift, no_more_attempts, clip_overflow,
// retranslation_disabled, retranslate_failed, judge_veto_drift);
// useThinking is "true" when the agent escalated to the reasoning model;
// useEnsemble (OPT-202) is "true" when the retranslate fanned out to
// multiple models. The two escalations are mutually exclusive in
// practice (the agent drops thinking when ensemble fires) but kept
// as independent labels so the dashboard can show "ensemble vs
// thinking" share without rewriting queries when the policy changes.
//
// Defensive defaulting on empty strings prevents an accidental
// "" label value (which Prometheus accepts but is hard to query).
func IncSegmentAgentDecision(kind, reason string, useThinking, useEnsemble bool) {
	if kind == "" {
		kind = "unknown"
	}
	if reason == "" {
		reason = "unknown"
	}
	thinkingLabel := "false"
	if useThinking {
		thinkingLabel = "true"
	}
	ensembleLabel := "false"
	if useEnsemble {
		ensembleLabel = "true"
	}
	segmentAgentDecisionsTotal.WithLabelValues(kind, reason, thinkingLabel, ensembleLabel).Inc()
}

func MetricsHandler() http.Handler {
	return promhttp.Handler()
}
